### ISSUE TITLE
The pre-compiled library seems to be broken... 

### ISSUE THREAD

**Issue by blackholebug** [hummat/registration#1]
I have tried to load the library but always encountered an error

this is the test code I'm using: 
`REGLIB = np.ctypeslib.load_library(libname="libregistration", loader_path="os.getcwd()")`

> OSError: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory

I tried to move the library to a path in $LD_LIBRARY_PATH$, and run:

`REGLIB = np.ctypeslib.load_library(libname="libregistration", loader_path="some path in  $LD_LIBRARY_PATH$")` 
still, the same error occurred. 

loading the other library in this path is just fine.

**Comment by hummat** [comment]
Hi @blackholebug, thanks for letting me know. I'll try to have a look asap.

**Comment by hummat** [comment]
I've just tried to replicate the problem on my system but didn't get the error. As this is only a wrapper for PCL, did you install PCL beforehand, e.g. `sudo apt install libpcl-dev` on Ubuntu? This should also install `libboost` on your system. I'll add this info to the readme.

I've pushed a new compiled version of `libregistration` for PCL 1.10. Could you try it out?

**Comment by blackholebug** [comment]
Hi hummat, that's exactly the problem! I actually have tried to install the PCL library after reporting this issue, and it worked well. Thank you for updating the readme file!

**Comment by unimusic** [comment]
Hi hummat, I am having the same problem now. I already did run the sudo apt install libpcl-dev. I can see the pcl-1.12 library in /usr/include/pcl-1.12/pcl. Is there something else I am missing? Thanks.

**Comment by hummat** [comment]
Hi @unimusic it's been a while that I've checked in on this project. It might be that PCL 1.12 is not backward compatible with PCL 1.10 for which there is a pre-compiled version of this library. Can you try with PCL 1.10? Otherwise, you should be able to compile this library to work with your version of PCL. Roughly:

1. Change PCL version in `CMakeList.txt`
2. mkdir build && cd build
3. cmake ..
4. make
5. Use `reglib.load_library` with the path to your newly compiled library
