### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by Zulex** [hummat/registration#2]
This seems like great work! I was exactly looking for a lightweight solution to implement in Python projects. As I am trying to combine it with Unity, windows is my only options. Any plans on supporting Windows?

**Comment by hummat** [comment]
Hi @Zulex, unfortunately not as I don't have lots of experience with development on Windows. If you could manage to install PCL following the official instructions for Windows as well as Python and CMake you should be able to compile the library yourself though.
Otherwise you could check out Open3D which implements a lot of registration functionality and has great Python bindings (it's by no means lightweight though). Best of luck!
